# from fduthesis: https://github.com/stone-zeng/fduthesis/blob/master/.github/workflows/test.yml

name: build

on:
  - push
  - pull_request

env:
  BUILD_DIR: build
  CTAN_URL: https://mirrors.rit.edu/CTAN
  DOC_DEPENDENCE: ctable listings hologo emoji
  NOTO_URL: https://noto-website-2.storage.googleapis.com/pkgs
  SED_REP_WITH_CLS_ARGS: s/\\documentclass\[\(.*\)\]/\\documentclass\[\1, fontset=none\]/

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[ci ubuntu]') || !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Noto and Times fonts
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get --yes install fonts-noto-cjk fonts-noto-cjk-extra ttf-mscorefonts-installer
      - name: Install TeX Live
        run: |
          export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
          curl -OL ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -zxf install-tl-unx.tar.gz
          pushd install-tl-20* && chmod +x install-tl
          ./install-tl --profile ../.github/workflows/texlive.profile --repository ${{ env.CTAN_URL }}/systems/texlive/tlnet/
          popd
          echo "$(cat DEPENDS.txt | tr '\n' ' ') ${{ env.DOC_DEPENDENCE }}" | xargs tlmgr install 
          echo "/tmp/texlive/bin/x86_64-linux" >> $GITHUB_PATH
      - name: Build user document (LuaLaTeX)
        run: |
          sed -i '${{ env.SED_REP_WITH_CLS_ARGS }}' shtthesis-user-guide.tex
          latexmk -pdflua -outdir=${{ env.BUILD_DIR }}/lualatex
      - name: Build user document (XeLaTeX)
        if: success() || failure()
        run: |
          latexmk -pdfxe -outdir=${{ env.BUILD_DIR }}/xelatex
      - name: Archive build outputs
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-build
          path: ${{ env.BUILD_DIR }}
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    if: ${{ contains(github.event.head_commit.message, '[ci macos]') || !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Install utilities
        run: |
          brew install gnu-sed
      - name: Install Noto and FangZheng fonts
        run: |
          for i in NotoSerifCJK NotoSansCJK; do curl -O ${{ env.NOTO_URL }}/$i.ttc.zip; done
          for i in FZKTK FZFSK; do curl -O https://bwh-jp-01.rundong.me/fonts/$i.TTF; done
          unzip -o "*.zip"
          cp -vf *.ttc *.TTF /Library/Fonts/
      - name: Install TeX Live
        run: |
          export PATH=/tmp/texlive/bin/universal-darwin:$PATH
          curl -OL ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -zxf install-tl-unx.tar.gz
          pushd install-tl-20* && chmod +x install-tl
          ./install-tl --profile ../.github/workflows/texlive.profile --repository ${{ env.CTAN_URL }}/systems/texlive/tlnet/
          popd
          echo "$(cat DEPENDS.txt | tr '\n' ' ') ${{ env.DOC_DEPENDENCE }}" | xargs tlmgr install 
          echo "/tmp/texlive/bin/universal-darwin" >> $GITHUB_PATH
      - name: Build user document (LuaLaTeX)
        run: |
          gsed -i '${{ env.SED_REP_WITH_CLS_ARGS }}' shtthesis-user-guide.tex
          latexmk -pdflua -outdir=${{ env.BUILD_DIR }}/lualatex
      - name: Build user document (XeLaTeX)
        if: success() || failure()
        run: |
          latexmk -pdfxe -outdir=${{ env.BUILD_DIR }}/xelatex
      - name: Archive build outputs
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: ${{ env.BUILD_DIR }}
  # Line wrap problem is difficult to resolve on windows.
  build-windows:
    runs-on: windows-latest
    name: Build on Windows
    if: ${{ contains(github.event.head_commit.message, '[ci windows]') || !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Windows (Simplified Chinese) fonts
        run: |
          "simhei.ttf", "simkai.ttf", "simfang.ttf" | ForEach-Object -Process {Invoke-WebRequest -Uri "https://bwh-jp-01.rundong.me/fonts/$_" -OutFile "C:\Windows\Fonts\$_"}
      - name: Install TeX Live
        run: |
          ${env:PATH} = "${{ github.workspace }}\tmp\texlive\bin\win32;" + ${env:PATH}
          Invoke-WebRequest -Uri ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl.zip -OutFile install-tl.zip
          Expand-Archive install-tl.zip -DestinationPath .
          Push-Location install-tl-*
          .\install-tl-windows --no-gui --profile ..\.github\workflows\texlive-win.profile --repository ${{ env.CTAN_URL }}/systems/texlive/tlnet/
          Pop-Location
          &tlmgr install @((Get-Content ./DEPENDS.txt) + "${{ env.DOC_DEPENDENCE }}".split())
          echo "${{ github.workspace }}\tmp\texlive\bin\win32" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Build user document (LuaLaTeX)
        run: |
          New-Item -Path "${{ env.BUILD_DIR }}\lualatex" -ItemType Directory
          Push-Location "${{ env.BUILD_DIR }}\lualatex"
          Copy-Item "..\..\shtthesis-user-guide.tex", "..\..\shtthesis.cls", "..\..\shanghaitech-emblem.pdf" -Destination .
          lualatex shtthesis-user-guide.tex
          biber shtthesis-user-guide.bcf
          lualatex shtthesis-user-guide.tex
          lualatex shtthesis-user-guide.tex
          Pop-Location
      - name: Build user document (XeLaTeX)
        if: success() || failure()
        run: |
          New-Item -Path "${{ env.BUILD_DIR }}\xelatex" -ItemType Directory
          Push-Location "${{ env.BUILD_DIR }}\xelatex"
          Copy-Item "..\..\shtthesis-user-guide.tex", "..\..\shtthesis.cls", "..\..\shanghaitech-emblem.pdf" -Destination .
          xelatex shtthesis-user-guide.tex
          biber shtthesis-user-guide.bcf
          xelatex shtthesis-user-guide.tex
          xelatex shtthesis-user-guide.tex
          Pop-Location
      - name: Archive build outputs
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: ${{ env.BUILD_DIR }}
