# from fduthesis: https://github.com/stone-zeng/fduthesis/blob/master/.github/workflows/test.yml

name: build

on:
  - push
  - pull_request

env:
  BUILD_DIR: build
  CTAN_URL: https://mirrors.rit.edu/CTAN
  DOC_DEPENDENCE: ctable listings hologo emoji
  NOTO_URL: https://noto-website-2.storage.googleapis.com/pkgs
  SED_REP_WITH_CLS_ARGS: s/\\documentclass\[\(.*\)\]/\\documentclass\[\1, fontset=none\]/

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[ci ubuntu]') || !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Noto and Times fonts
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get --yes install fonts-noto-cjk fonts-noto-cjk-extra ttf-mscorefonts-installer
      - name: Install TeX Live
        run: |
          export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
          curl -OL ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -zxf install-tl-unx.tar.gz
          pushd install-tl-20* && chmod +x install-tl
          ./install-tl --profile ../.github/workflows/texlive.profile --repository ${{ env.CTAN_URL }}/systems/texlive/tlnet/
          popd
          echo "$(cat DEPENDS.txt | tr '\n' ' ') ${{ env.DOC_DEPENDENCE }}" | xargs tlmgr install 
          echo "/tmp/texlive/bin/x86_64-linux" >> $GITHUB_PATH
      - name: Build user document (LuaLaTeX)
        run: |
          sed -i '${{ env.SED_REP_WITH_CLS_ARGS }}' lzp-shtthesis.tex
          latexmk -pdflua -outdir=${{ env.BUILD_DIR }}/lualatex
      - name: Build user document (XeLaTeX)
        if: success() || failure()
        run: |
          latexmk -pdfxe -outdir=${{ env.BUILD_DIR }}/xelatex
      - name: Archive build outputs
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-build
          path: ${{ env.BUILD_DIR }}
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
